name: Tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        # 17.x Does not support the NodeJS Test Runner
        node-version: [16.x, 18.x, 19.x, 20.x]

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3

      - name: Setup NodeJS - ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Run Tests
        run: npm run test

      #- name: Codecov Upload
      #  if: always() # Needed to ensure coverage is commited even on test failure
      #  uses: codecov/codecov-action@v3
      #  with:
      #    files: ./coverage/clover.xml
